### PR TITLE
Issue #3 submission

### PR DESCRIPTION
**Pull request by benchblocker**
Would appreciate any feedback. Working on visuals now.

### CODE REVIEW

**Comment by kristjank** [comment]
tnx for you submission, but this topic is already taken - please check the project overview and double check with us before continuing writing on the topic...

you can see the status of open topics (to-do) and topics being worked on (in progress) in the project overview page here https://github.com/ArkEcosystem/docs/projects/1 

From github point of view - you did everthing ok, maybe pay attention to naming of the file that should be issueNumber_Title.md - for example: 03_ConsensusMechanisms (so we can correlate the topic to the task).

Let us know if you need anything else

**Comment by benchblocker** [comment]
@kristjank thank you for the quick response. I've been in touch with Rok over Slack via the name "Cattsby" with regard to covering issue 3 and 6. I did noticed that there was already a submission for this issue, but that just pushes me to make the content better so I'd appreciate any critiques on the piece.

**Comment by kristjank** [comment]
hi, thanks for you work and efforts. You started out very good, just more details and content and maybe images that tell the story are also welcome...

Did you find any other topics you would like to cover @benchblocker

**Comment by benchblocker** [comment]
@kristjank Hope to have the #3 visuals submitted by next Friday, at the very latest. My university work is winding down, and I should have much more time to work on this project in the coming weeks. 

Regarding more content, besides #6, I'm nearing completion on my own personal piece that simplistically explains how blockchain networks increase network capacity (TPS) and achieve higher levels of scalability — through simple math and great visuals/analogies. I'm using v2 as the prime example to compare to Bitcoin. I cant find any content out their that explains these topics they way I have so I'm quite excited to share it.

**Pull request closed without merging**
