### PR TITLE
docs(glossary): update crypto definitions

### PR DESCRIPTION
**Pull request by Nikolaj-K**
Clarify or correct statements, mostly in glossary.

### CODE REVIEW

**Review by sleepdefic1t — CHANGES_REQUESTED** [review]
This is actually not correct.. not your fault though, the original text is not very accurate.

```diff
- Digital wallets containing, or previously having contained ARK, are identified by wallet addresses strings. A funded addresses public key, if one exists, may not be public and thus be unknown to the network. In that case, it is referred to as a `cold wallet`.
+ Digital wallets represent a public and private keyPair. They typically produce one or many wallet addresses and are used to digitally sign data. Depending on the type of wallet, the public key may not be known until its corresponding privateKey has been used to sign data publicly (e.g. sending a transaction). In the context of the Wallet API, a wallet is a specific address or publicKey.
```

**Comment by Nikolaj-K** [comment]
@sleepdefic1t What's not correct?

**Comment by Nikolaj-K** [comment]
I'd start with an Hello instead of an insinuation I blundered in my correction. I don't think I did. Note that in my first sentence, I don't characterize a wallet and in the second I speak of an address. But in any case, note that this is not the glossary section for `wallet` but the pretext for the wallet API doc. Maybe we can debate about the semantics of the word "identified" or whether there's an epistemological aspect to when a funded address could be called a cold wallet. I'd still like to know what you mean when you say I'm not right.

**Comment by sleepdefic1t** [comment]
@Nikolaj-K 

Whoa, now.
Never meant any kind of insult, no need to take it as such.

My point is that the original text is not correct so any updates to THAT text will still be not correct. I was only looking for a way we can be more concise _now_ since you’re already updating it.

> Original: Wallets are addresses containing, or previously having contained ARK.

> Your update: Digital wallets containing, or previously having contained ARK, are identified by wallet addresses strings. 

Whether a wallet contains ARK has nothing to do with the address.

> Original: A wallet's public key may be unknown to the network, in that case, it is referred to as a `cold wallet`.

> Your update: A funded addresses public key, if one exists, may not be public and thus be unknown to the network. In that case, it is referred to as a `cold wallet`.

That’s not what a cold wallet is, and the main point is that a PublicKey may not be known for an Address if it has never sent a transaction. Which is relevant because you cannot search the Wallet API with a PublicKey from an Address with no spends.

My suggestion—very much open to discussion: 

>  Digital wallets represent a public and private keyPair. They typically produce one or many wallet addresses and are used to digitally sign data. Depending on the type of wallet, the public key may not be known until its corresponding privateKey has been used to sign data publicly (e.g. sending a transaction). In the context of the Wallet API, a wallet is a specific address or publicKey.

...and I’m not even 100% happy with that.
That’s why I shared it with you hoping for input vs just accepting and going back later.

At any point, I’m glad that you’re contributing.

The glossary page is perfect as submitted, absolutely bulletproof. You nailed the WIF definition beautifully, for instance.

The wallet API page, I’d prefer more clarity if we’re updating it.

**Comment by Nikolaj-K** [comment]
Whoa, now.
Yeah fair enough, I didn't want to be rude either.

Let me cite again the original text (that we both don't like)

>Wallets are addresses containing, or previously having contained ARK. A wallet's public key may be unknown to the network, in that case, it is referred to as a `cold wallet`.	

Here the author was identifying wallets with addresses on the ledger and was then implying every address corresponds to a public key. I was doing an edit to remove this connection.

Your edit is fine but more an elaboration on the wallet concept as a whole. As I pointed out above, the paragraph we're discussing here is not one attempting to define wallet (or cold wallet, etc.) like e.g. in the glossary section of the docs (until now at least).
You can of course edit as you like. 

>Whether a wallet contains ARK has nothing to do with the address.

I don't see how this invalidates the sentence

>Digital wallets containing, or previously having contained ARK, are identified by wallet addresses strings.

Is your issue that wallets that have never been used also have addresses tied to them?

 >That’s not what a cold wallet is, and the main point is that a PublicKey may not be known for an Address if it has never sent a transaction. Which is relevant because you cannot search the Wallet API with a PublicKey from an Address with no spends.

I think there's 2 or more notions of "cold wallet" floating around, I'm not sure which one you want to prefer here. I suppose many exchanges would already use the terminology just for wallets whos key info is air gapped from the internet, irregardless of its public keys be or not (do we want to say a wallet can be a cold wallet even if it's compromised in the minor sense of having an outgoing transaction on-chain?). Either way, I'll just revert back the changes on the non-glossary side and we can leave it open or for later. 

I might get to it if I build something with the network, I just saw the link to the repo in that youtube vid.

**Comment by sleepdefic1t** [comment]
> Here the author was identifying wallets with addresses on the ledger and was then implying every address corresponds to a public key. I was doing an edit to remove this connection.
...
Your edit is fine but more an elaboration on the wallet concept as a whole. As I pointed out above, the paragraph we're discussing here is not one attempting to define wallet (or cold wallet, etc.) 

A central issue here is that Wallets & Addresses are used interchangeably for ARK atm. Which is technically inaccurate.

This likely happened because ARK is a stateful system with no concept of change addresses/Utxo.

I agree, the level of info I suggested is more suited for the glossary section.

# 
> > Whether a wallet contains ARK has nothing to do with the address.
>
> I don't see how this invalidates the sentence

It doesn’t really invalidate anything, it’s just not that relevant.

Funds in this context are only relevant when there are spends. i.e. whether the PublicKey is known and able to be used to search for a Wallet/Address using the Wallet REST API.

Even then, there are cases where there are no funds at all but the PublicKey _is_ known.

```json
{
  "data": {
    "address": "DCbAu9ZwvAgAZSx9C2CJQ6DBq4whzGMqMS",
    "publicKey": "03d1bb32b9ce1984ae4b8916418962442b9d8791907e3e892faa9533fddadb8f4c",
    "balance": "0",
    "nonce": "0",
    "attributes": {
      "multiSignature": {
        "publicKeys": [
          "022a40ea35d53eedf0341ffa17574fca844d69665ce35f224e9a6b1385575044fd",
          "037fde73baaa48eb75c013fe9ff52a74a096d48b9978351bdcb5b72331ca37487c"
        ],
        "min": 2
      }
    }
  }
}
```
> [https://dwallets.ark.io/api/wallets/DCbAu9ZwvAgAZSx9C2CJQ6DBq4whzGMqMS](https://dwallets.ark.io/api/wallets/DCbAu9ZwvAgAZSx9C2CJQ6DBq4whzGMqMS)  
[https://dwallets.ark.io/api/wallets/03d1bb32b9ce1984ae4b8916418962442b9d8791907e3e892faa9533fddadb8f4c](https://dwallets.ark.io/api/wallets/03d1bb32b9ce1984ae4b8916418962442b9d8791907e3e892faa9533fddadb8f4c)

#

>> Digital wallets containing, or previously having contained ARK, are identified by wallet addresses strings.
>
> Is your issue that wallets that have never been used also have addresses tied to them?

This again kinda goes back to the fact that Address and Wallet are used interchangeably and that it doesn’t necessarily have a bearing on whether the PublicKey is known.

Your update gets much closer to the point, but since it doesn’t really address the relationship to PublicKey availability, it feels like it could be omitted from that altogether.

#

> I think there's 2 or more notions of "cold wallet" floating around, I'm not sure which one you want to prefer here...

I typically think of a “cold wallet” as an air-gapped wallet.

Regardless.. whether or not a Wallet Address has funds or outgoing transactions doesn’t necessarily decide whether or not it’s PublicKey is known

We can only say with certainty that an Address with spends has a known PublicKey, otherwise it may or may not.

#

Needless to say, there are a lot of nuances and exceptions that are hard to nail down concisely.

Perhaps we can approach this section later and really do it some justice. I know this has certainly helped!

I absolutely appreciate you taking a go at this, and I’m happy to have had these discussions with you.

Thank you!

**Review by sleepdefic1t — APPROVED** [review]

**Pull request merged**
