### PR TITLE
05 Peers Nodes

### PR DESCRIPTION
**Pull request by dustindreifuerst**
Infographic as disccussed with Mr. Černec

-Links will need to be redone when the other contributors finish and commit. 
*ark aces link is correct

- I understand this will need to be continued to be updated as new ECL nodes are created, etc.  I am more than happy to continue working on this project!

### CODE REVIEW

**Comment by kristjank** [comment]
Hi,

I suggest we stay on the same terminology... i.e.
Full node is a relay node
Delegate node is also known as forging node

Also please structure your PR according to the folders. As this is task: https://github.com/ArkEcosystem/docs/issues/5 tagged with blockchain mechanics I suggest the following:

1. create folder on root named "BlockchainMechanics"
2. create subfolder for your task starting with number of the task. For this example you have 05_WhatArePeerNodes...
3. please try to answer all the topics defined in the task, or shout out for help if you need anything. There are still answers missing to the topics defined in task https://github.com/ArkEcosystem/docs/issues/5.

best

**Comment by dustindreifuerst** [comment]
Apologies!

i sdidnt see these threads for the topics with specific points to cover! THis has been my first time on Github. I will redo all my commits to reflect this!

I will also change the infographics as well.

Once again, sorry about that, will get you what you need asap

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by kristjank** [comment]
No problem, let me know when you have it...

Think about some images also... peer-2-peer network, distributed network.. etc

**Comment by dustindreifuerst** [comment]
updated Peers/nodes. continuing to work on transactions/blocks.

let me know what you think

**Comment by kristjank** [comment]
much better - do you want to add anything more?... or is a PR complete one?

**Comment by kristjank** [comment]
Ok great - please let me know when PR is complete for full review...

**Comment by dustindreifuerst** [comment]
Is there any reason i cant publish a new branch? im trying to commit 08_Transactions seperately but theres any authetnication error publishing branch via desktop

**Comment by kristjank** [comment]
is this PR done? can we review - please update me

**Comment by dustindreifuerst** [comment]
Sorry Yes. 05 is ready for review as is 08. i believe i forked it to its own branch according to the youtube tutorials on github i watched. I thought i had sent an email to you letting you know? if it didnt go through i apologize.

Thank you for your patience with a github noob!

Also i wanted make sure the color schemes are uniform across this whole documentation scheme so let me know if you need any infographics updated with specific colors, etc. Or if you would like i can make new infographics for other commits, etc. whatever you guys need let me know

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request merged**
