### PR TITLE
docs(public-rest-api): update wallets descriptor

### PR DESCRIPTION
**Pull request by sleepdefic1t**
## Summary

Update Wallets Endpoint descriptor to be more clear.

## Checklist

- [x] Ready to be merged

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@Nikolaj-K
This might be more readable and to the point.
What are your thoughts?

**Comment by Nikolaj-K** [comment]
Sounds like the appropriate amount of info the section, go for it.

---- 

Why I was zooming in on the wallet info provided here in the first place was because 2 days ago I was [testing the cases made here](https://gist.github.com/Nikolaj-K/3b8c8b3674d6b850a91faa505ce64e99) with python. 
Is it actually possible to send tx using just an API in this way (possibly with a bunch of data tying to a private key of choice)?

**Comment by sleepdefic1t** [comment]
@Nikolaj-K 

> Is it actually possible to send tx using just an API in this way (possibly with a bunch of data tying to a private key of choice)?

Well, the tx would still need to be signed via Crypto SDK API.. but there’s no key server/wallet node to deal with, if that’s what you mean.

You just construct the Tx and sign it, then POST it to the `/transactions` endpoint as such:

```json
{
    "transactions": [
        {
	    "version": 2,
	    "network": 23,
	    "type": 0,
	    "nonce": "1",
	    "senderPublicKey": "03a02b9d5fdd1307c2ee4652ba54d492d1fd11a7d1bb3f3a44c4a05e79f19de933",
	    "fee": "10000000",
	    "amount": "100000",
	    "expiration": 0,
	    "recipientId": "AJWRd23HNEhPLkK1ymMnwnDBX2a7QBZqff",
	    "signature": "4f01bd21828a633a3c821b9984fe642deab87237b99e62a543ca6948ff1d6d32f2475ada1f933da0591c40603693614afa69fcb4caa2b4be018788de9f10c42a",
	    "id": "8c85167cb1ca6f70e350f30173deb4c0a00ce7169d04f78fe4e4bcf2c3a75214"
        }
    ]
}
```
 > ^ example transfer payload

More info here:
* [https://ark.dev/docs/sdk/python/complementary-examples](https://ark.dev/docs/sdk/python/complementary-examples)

#

We also have a Discord if you ever have more questions or need assistance: https://discord.ark.io

Thanks again for the help!

**Comment by sleepdefic1t** [comment]
@faustbrian gtg 👍

**Pull request merged**
