### PR TITLE
07 Blockchain communication explanation initial PR

### PR DESCRIPTION
**Pull request by BlockchainDeal**
working

### CODE REVIEW

**Comment by kristjank** [comment]
@BlockchainDeal nicely done with the basic intro. Would like to see a bit more documentation in here, such as p2p layer or distributed layer explained - for the reader to understand what happens when a transaction is sent to the node, then the node validates it and sends it to other peers/servers in the network... .. maybe some kind of graphic would useful.

**Comment by BlockchainDeal** [comment]
alright working on it

**Comment by kristjank** [comment]
is this PR done? can we review - please update me

**Comment by kristjank** [comment]
@BlockchainDeal  is this completed?

**Comment by BlockchainDeal** [comment]
@kristjank no, refactoring this when possible for a more comprehensive version

**Comment by kristjank** [comment]
@BlockchainDeal let me know when done

**Comment by kristjank** [comment]
@BlockchainDeal so you gonna refactor this one together with the latest restructure commit...

**Comment by kristjank** [comment]
will close this - to get more structure. please update with new PR after tree-clean is done. 

Thanks @BlockchainDeal

**Pull request merged**
